apiVersion: v1
kind: Service
metadata:
  labels:
    app: labels-db
  name: labels-db
  namespace: citrix-system
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: labels-db
status:
  loadBalancer: {}
