apiVersion: v1
kind: ServiceAccount
metadata:
  name: labels-db
  namespace: citrix-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: labels-db-cr
  labels:
    app: labels-db
rules:
- apiGroups: [""]
  resources:
  - pods
  - services
  - deployments
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: labels-db-crb
  labels:
    app: labels-db
roleRef:
  kind: ClusterRole
  name: labels-db-cr
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: labels-db
  namespace: citrix-system
---